spring:
  application:
    name: stocks-api
  datasource:
    name: stocksDB
    url: jdbc:h2:mem:stocksDB;DB_CLOSE_DELAY=-1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level: INFO

